[package]
name = "asite"
version = "0.1.0"
authors = ["Aria Fallah <aria@fallah.us>"]
edition = "2018"

[dependencies]
toml = "0.5.6"
serde = { version = "1.0.110", features = ["derive"] }
anyhow = "1.0.31"
walkdir = "2.3.1"
