[package]
name = "generate"
version = "1.0.0"
edition = "2018"

[dependencies]
toml = "0.5.6"
serde = { version = "1.0.110", features = ["derive"] }
anyhow = "1.0.31"
walkdir = "2.3.1"

[[bin]]
name = "generate"
path = "./generate.rs"
